---
- name: Create additional users
  user:
    name: "{{ item.login }}"
    home: "/home/users/{{ item.login }}"
    uid: "{{ item.uid }}"
    group: "users"
    update_password: on_create
  when: item.login != ""
  with_items: "{{ users_list }}"

- name: Add users to sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ item.login }}"
    line: "{{ item.login }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  when: item.login != ""
  with_items: "{{ users_list }}"

- name: Set permissions on /home/users/shared
  file:
    path: "/home/users/shared"
    owner: "centos"
    group: "users"
    state: directory
    mode: "u=rwx,g=rwx,o=rx"

- name: Add users ssh keys
  lineinfile:
    path: "/home/users/{{ item.login }}/.ssh/authorized_keys"
    create: yes
    line: "{{ item.key }}"
    state: present
    owner: "{{ item.login }}"
    group: "users"
    mode: "0600"
  when: item.login != ""
  with_items: "{{ users_list }}"

- name: Set permission on ssh dir
  file:
    path: "/home/users/{{ item.login }}/.ssh" 
    owner: "{{ item.login }}"
    group: "users"
    mode: "0700"
  when: item.login != ""
  with_items: "{{ users_list }}"

- name: Add centos ssh keys
  blockinfile:
    path: /home/centos/.ssh/authorized_keys
    create: yes
    block: "{{ item.key }}"
  when: item.login != ""
  with_items: "{{ users_list }}"

- name: Set owner on home
  file:
    path: "/home/users/{{ item.login }}" 
    owner: "{{ item.login }}"
    group: "users"
    recurse: yes
  when: item.login != ""
  with_items: "{{ users_list }}"
  
- name: Add authorized keys file to AuthorizedKeysFile
  lineinfile: 
    dest=/etc/ssh/sshd_config
    backup=True
    backrefs=True
    state=present
    regexp='^(AuthorizedKeysFile(?!.*\b/home/users/{{ item.login }}/.ssh/authorized_keys\b).*)$'
    line='\1 /home/users/{{ item.login }}/.ssh/authorized_keys'
  when: item.login != ""
  with_items: "{{ users_list }}"

- name: Stop and Start ssh
  service:
    name: sshd
    state: restarted